name: Grype Vulnerability Scan

on:
  # Allows you to trigger the scan manually
  workflow_dispatch: 

jobs:
  grype-scan:
    runs-on: ubuntu-latest
    name: Run Grype SCA
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Anchore Grype Scan
        uses: anchore/scan-action@v7
        with:
          # Tells Grype to scan the entire repository directory
          path: "."
          
          # Set to false so the workflow doesn't crash on the first vulnerability it finds.
          # This allows you to see the complete list in the logs.
          fail-build: false
          output-format: table 
